name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - "sweets/ci-cd"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Debug Secrets
        run: |
          echo "DROPLET_IP is set: ${{ secrets.DROPLET_IP != '' }}"
          echo "DROPLET_USER is set: ${{ secrets.DROPLET_USER != '' }}"
          echo "DROPLET_PASSWORD is set: ${{ secrets.DROPLET_PASSWORD != '' }}"

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            echo "Connected to Droplet"
            # Create app directory if it doesn't exist
            mkdir -p ~/myco-token-indexer
            cd ~/myco-token-indexer

            # Initialize git repository if it doesn't exist
            if [ ! -d .git ]; then
              git init
              git remote add origin https://github.com/SweetmanTech/myco-token-indexer.git
            fi

            # Fetch latest code and handle local changes
            git fetch --all
            git stash
            git checkout -B sweets/ci-cd origin/sweets/ci-cd
            git reset --hard origin/sweets/ci-cd
            git stash pop || true  # Apply stashed changes if any, ignore if fails

            echo "Current branch:"
            git branch --show-current
            echo "Git status:"
            git status

            # Ensure correct Node.js version
            source ~/.nvm/nvm.sh
            nvm use 20

            # Install dependencies
            npm install

            # Debug: List contents of the lib directory
            echo "Contents of ~/myco-token-indexer/lib:"
            ls -l ~/myco-token-indexer/lib

            # Debug: Show contents of indexer.mjs
            echo "Contents of ~/myco-token-indexer/indexer.mjs:"
            cat ~/myco-token-indexer/indexer.mjs

            # Update indexer.mjs
            echo "Updating indexer.mjs"
            sed -i 's/from "\(\.\/lib\/[^"]*\)"/from "\1.js"/' ~/myco-token-indexer/indexer.mjs

            # Update import paths in lib files
            find ~/myco-token-indexer/lib -name "*.js" -type f -exec sed -i 's/from "\([^"]*\)"/from "\1.js"/' {} +
            find ~/myco-token-indexer/lib/stack -name "*.js" -type f -exec sed -i 's/from "\([^"]*\)"/from "\1.js"/' {} +

            # Remove duplicate .js extensions
            find ~/myco-token-indexer -name "*.js" -type f -exec sed -i 's/\.js\.js/.js/g' {} +

            # Debug: Show updated contents of indexer.mjs
            echo "Updated contents of ~/myco-token-indexer/indexer.mjs:"
            cat ~/myco-token-indexer/indexer.mjs

            # Debug: Show Node.js version
            node --version

            # Start or restart the app using PM2
            if pm2 list | grep -q "myco-token-indexer"; then
              pm2 restart myco-token-indexer --update-env --cwd ~/myco-token-indexer
            else
              pm2 start npm --name "myco-token-indexer" --cwd ~/myco-token-indexer -- run start
            fi
