name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - "**" # This will trigger the workflow on push to any branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Debug Secrets
        run: |
          echo "DROPLET_IP is set: ${{ secrets.DROPLET_IP != '' }}"
          echo "DROPLET_USER is set: ${{ secrets.DROPLET_USER != '' }}"
          echo "DROPLET_PASSWORD is set: ${{ secrets.DROPLET_PASSWORD != '' }}"

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            echo "Connected to Droplet"
            # Create app directory if it doesn't exist
            mkdir -p ~/myco-token-indexer
            cd ~/myco-token-indexer

            # Initialize git repository if it doesn't exist
            if [ ! -d .git ]; then
              git init
              git remote add origin https://github.com/SweetmanTech/myco-token-indexer.git
            fi

            # Fetch latest code
            git fetch --all
            git reset --hard origin/main

            # Install dependencies
            npm install

            # Start or restart the app using PM2
            if pm2 list | grep -q "myco-token-indexer"; then
              pm2 restart myco-token-indexer
            else
              pm2 start npm --name "myco-token-indexer" -- run start
            fi
